### ISSUE TITLE
Disable seat when using --disable-input

### ISSUE THREAD

**Issue by tleydxdy** [any1/wayvnc#136]
With --disable-input the seat is not doing anything, but would cause wayvnc to fail if no seat is available from the compositor. maybe the option should even be renamed to disable-seat or something.

I patched in a simple check at seat allocation and it seem to work fine, but probably the right impl is to change all the keyboard/mouse stuff to check for if seat == null instead of disable-input

**Comment by any1** [comment]
disable-input is a good enough name. Most people don't know what a "seat" is anyhow.
The check should be for "disable-input" because that makes things explicit. You wouldn't want inputs to fail silently and be left scratching your head. Refusing to start without input or `--disable-input` draws attention to the problem.

**Comment by tleydxdy** [comment]
makes sense

**Comment by tleydxdy** [comment]
closed by #137
