### ISSUE TITLE
Warning: ../src/ctl-server.c: 633: Failed to bind unix socket: Address already in use

### ISSUE THREAD

**Issue by suncore** [any1/wayvnc#180]
When trying to start wayvnc I get this error:
`Warning: ../src/ctl-server.c: 633: Failed to bind unix socket: Address already in use`
and wayvnc does not start.
I think this is because my previous instance of wayvnc did not shut down cleanly and left this socket in the file system:
```
$ ls -l $XDG_RUNTIME_DIR/wayvncctl 
srwxrwxr-x 1 hch hch 0 nov 11 15:58 /run/user/1000/wayvncctl=

```
This should have been removed in ctl_server_stop but that was never run and now wayvnc can't start. I can remove it manually but I do think wayvnc should always remove this before starting up.

**Comment by any1** [comment]
This should also be at the "ERROR" log level rather than "Warning". Anything that causes the program to stop running is an "ERROR".

It's probably not good to just throw away the socket if another wayvnc instance is already running. We should query the socket if it exists and see if there is anything listening on it. Only, if no reply is given can we `unlink` it.

@lack, can you take a look at this?

**Comment by lack** [comment]
On it!
