### ISSUE TITLE
While wayvnc is running, wlopm reports all outputs as off

### ISSUE THREAD

**Issue by ikirudennis** [any1/wayvnc#283]
- **Version:**
  - ```
    wayvnc: 0.7.2
    neatvnc: 0.7.1
    aml: 0.3.0
    OS: Fedora 39
    wlopm: 0.1.0
    wlroots: 0.17.1

- Describe how to **reproduce** the problem
1. without `wayvnc` running, `wlopm` shows any and all appropriate outputs as `on`
2. while `wayvnc` is running, `wlopm` now reports all outputs as `off`
3. killing `wayvnc` results in `wlopm` reporting all outputs as `on` once again

Is this expected functionality or a bug? This renders `wlopm` non-functional in `swayidle` screen timeout configurations, so the screen perpetually stays on. Is there a configuration option which can be applied which would allow `wayvnc` to be running and also let `wlopm` control the screens? (Or is this an inherent conflict between the two systems due to the way wayland works, or something?) This took a while to track down as a reason for `wlopm` not recognizing the screens and thus staying always on. And I couldn't find an issue tracker for `wlopm` so hopefully this is the right place to report this kind of side effect of the two running together.

**Comment by any1** [comment]
The utility of a trace log is not contingent upon whether it's a crash or not.

Anyhow, the captured output needs to be enabled for capturing to work because nothing will be drawn to it otherwise. WayVNC uses the power management protocol to turn on the output when a client connects. Perhaps this mechanism interferes with wlopm. We could add a flag to disable power management in wayvnc, but calling this a bug seems a bit of a stretch.

**Comment by any1** [comment]
Power management will now be turned on only while a user is connected. That should take care of this problem.
