### ISSUE TITLE
Issue with multiple IP addresses

### ISSUE THREAD

**Issue by ghollingworth** [any1/wayvnc#285]
Andri,

Tried this last night on my Pi at home, which just so happened to have both an Ethernet connection and was connected to WiFi, because of that ip a returns two matches so my IP ends up containing "192.168.123\n192.168.1.135\n" This will then fail the openssl call (although silently because set -e isn't set so it continues blindly...)

https://github.com/any1/wayvnc/blob/6975b25f000ced3330cbdb134aa47c1c5da7f44a/pios-control/usr/sbin/wayvnc-generate-keys.sh#L22

Just trying to understand what you're doing here, and I would think it's a bad idea to put dynamic IP addresses into the certificate anyway (which is what I've got, from my router)...

Not sure what the right thing is, possibly fix the multiple IP addresses, or remove the IP address completely from the openssl call?

**Comment by any1** [comment]
Originally, I did the same thing as here:
https://github.com/RPi-Distro/raspi-config/blob/71b703c7737988d631b3fafc27caa0fbbe4c3ed8/raspi-config#L968
but that was also broken because it tended to choose 127.0.0.1 instead of the intended address. However, I forgot to limit the result to a single address.

We could add multiple addresses or do what the original thing did and just pick the first one.

I also have mixed feelings about this because these can change after the certificate has been generated. DHCP leases usually last a very long time, so that's not really a problem, but the user might decide to enable ethernet/wifi afterwards or they might decide to set a static IP for either. In any case, this isn't particularly robust.

We could recommend that users set a unique host name and connect using the mDNS name; e.g. gordons-pi5.local, but most people won't read that recommendation or they will persist in using IP addresses because that's how they've always done things. Frankly, I tend to use IP addresses on local networks myself. And then there's IPv6...

I'm not sure if this would work, but maybe we could have a separate signing certificate that doesn't change and have users add that to their client. Then we could generate a new key and cert every time that any address changes and sign with the static signing key.

**Comment by ghollingworth** [comment]
I must admit, I'm unsure what the behaviour would be if this was wrong, for example, if a device's DHCP address changes, does this mean that the certificate will become invalid if the user types the new ip address to connect to the client?

Does that just mean it'll ask again to accept the certificate (and check the fingerprint?) Or will it just refuse point blank to connect to a device on which a certificate matches...  (A bit like with SSH if the certificate has changed for a device you actually need to remove the old certificate from known_hosts)

I would think in that situation just the "$HOSTNAME" would be fine...

Is it possible to use the Ethernet / WiFi MAC address instead?  That at least will not change for a known piece of hardware...

Gordon

**Comment by any1** [comment]
What the user will see if the correct IP address is missing from the certificate is a warning telling them that "Hostname does not match the server certificate.

![image](https://github.com/any1/wayvnc/assets/2663782/4d119c34-8737-4995-9209-4d73da120ffb)

If the certificate changes, the user will see this notice:

![image](https://github.com/any1/wayvnc/assets/2663782/77704059-6248-4e2b-ace5-9e84f3a49225)

Both of these notices offer the user to continue. The difference is that the former happens every time if the certificate doesn't have the right IP, but the latter happens every time that the certificate is regenerated.

I don't think that it's possible to use the MAC address instead.

**Comment by ghollingworth** [comment]
I think basing a certificate on what is a dynamically assigned IP address is a bad idea.  In general, depending on the quality of the router you may be right in that the same device will tend to keep getting the same IP address when it is renewed, but it does depend on how many devices there are, in total, depending on the default range (usually /24) and how likely it is those devices may be turned on/off and therefore the address gets reassigned.

I would think it would be better to just use the hostname or mDNS qualified hostname if that's available.  In future, we're going to encourage users to name the Pis that are installed by default (I find it difficult when I have more than one thing on my home network called "raspberrypi") so hopefully that would be more unique but at the same time less likely to just change...

Gordon

**Comment by any1** [comment]
I removed the IP and added the local domain. I also switched from RSA to ECDSA with 384 bit key and SHA-384.

**Comment by any1** [comment]
@spl237, it seems that the newly released package is missing these changes. I helped some guy on IRC who ran into this issue.

**Comment by spl237** [comment]
When were the changes added to the pios branch?

**Comment by any1** [comment]
January 11

**Comment by spl237** [comment]
Ah. It looks like you made that change and didn't bump the version number in the debian/control file, so when I rebuilt the package, it would have had the same version number as the previous version and hence probably got lost in our apt repo. Could you please update the version number in debian/control accordingly, and then I can pull and rebuild?

**Comment by any1** [comment]
Done.
