### ISSUE TITLE
Characters are randomly dropped.

### ISSUE THREAD

**Issue by dnfm** [any1/wayvnc#35]
To ensure this isn't a specific problem to the client, I've tried 4 different vnc clients, but they all exhibit the same behaviour.

When connected to a wayvnc instance, often characters are dropped from input.

And very occasionally, modifiers get stuck.  Smacking the modifier again turns it off, but possibly after it's thrown all sorts of chaos around by moving windows, changing focus, deleting text, etc.

The dropped character issue is especially bad when pressing more than one letter at a time (like pressing shift-letter to get an upper-case letter.)

**Comment by any1** [comment]
Version?

**Comment by dnfm** [comment]
HEAD from git master as of this morning. (Same with aml and neatvnc.)

**Comment by capelito** [comment]
Hi, I use wayvnc 0.1.2 with sway 1.4 and wlroots 0.10.1 on archlinux and have the same problem. Additionally keys gets stuck very often when I press Shift and some other letter. It looks like it always happens when I release the Shift key a little bit earlier than the letter. It's similar to https://github.com/TigerVNC/tigervnc/issues/345

Normally i use tigervnc as client but I tested it with the current versions of gtk-vnc, krdc, vinagre, remmina, tightvnc and ultravnc (ultravnc I tried from an windows client) but the symptoms happen in all of them.

Is there something I can do to help to debug this problem?
Thanks

**Comment by any1** [comment]
It seems that this could be considered a client bug. Clients also seem to do things a bit differently. Here is debug output from vinagre for the sequence shift down, f down, shift up, f up:
```
DEBUG: symbol=Shift_L level=0 code=LFSH pressed
DEBUG: symbol=F level=1 code=AC04 pressed
DEBUG: symbol=Shift_L level=0 code=LFSH released
ERROR: Failed to match level on symbol: F
```
I'll try to relax the matching criteria, but there's a chance that might cause other issues.

**Comment by dnfm** [comment]
FWIW, it's definitely worse on shift-ed characters, but it does drop some random unshifted characters too.

I don't know if speed has anything to do with it, but I type in the vicinity of 140wpm.

And like capelito above, I've also experienced it in vinagre, the official vnc client, and at least 2 other clients whose names escape me at the moment.

**Comment by any1** [comment]
I've pushed changes now that relax the matching criteria and add some extra debug output. It would be good to know if it solves things and if it introduces some new issues, especially with non-us layouts.

The proper solution would really be to create a new pseudo encoding (extension) that uses keycodes instead of symbols and post patches for it to all the major open source clients. An extension for setting keyboard layouts would also be useful.

**Comment by capelito** [comment]
Thanks for the quick adjustment. I just tested it quickly with the tigervnc viewer (us and german keyboard layout). For me the "shift key stuck problem" is fixed, before it happened all the time and now after 30 minutes of testing there was no single problem.

I'm not sure if the change also helped avoiding the dropping characters, this problem I only had rarely and more random. I will test more tomorrow.

**Comment by dnfm** [comment]
So I've done a git pull and compiled the latest commits, and the issue seems to be completely eradicated.  I am seeing no more dropped characters at all.  Only mistakes now are my own stupidity.

I'm seeing no new/different issues as a result, either, but it's only been an hour or two.

**Comment by any1** [comment]
Ok, thanks for reporting the issue and testing. I'll keep this open for a day or so. Please report back if you run into something.

**Comment by capelito** [comment]
Today I remotely worked for 6 hours and I didn't have any issues. So for me it looks good. Thanks again for the fast fix.

**Comment by any1** [comment]
Thanks for reporting back! I'll call it fixed then.
