### ISSUE TITLE
no shaders anymore?

### ISSUE THREAD

**Issue by lyssdod** [any1/wayvnc#56]
Just out of curiosity, why did you decide to switch to pixman?

https://github.com/any1/wayvnc/commit/c89ddb33c98d3e13af3dc9888d84f75c7857b008

**Comment by any1** [comment]
* Less code => easier to maintain
* Fewer dependencies
* Better portability
* Does not appear to perform any worse on my computer
* Actually performs better on raspberry pi 3

I am thinking of bringing back EGL for the purpose of reading DMABUFs though since GBM appears to perform quite inconsistently on different platforms.

**Comment by lyssdod** [comment]
I see, thanks
