### ISSUE TITLE
Keyboardlayout switches to english

### ISSUE THREAD

**Issue by gabm** [any1/wayvnc#6]
I started it up for testing and it seems to work very well on first glance.. nice work!. Anyway, my keyboard layout switched to english and doesnt turn back after stopping wayvnc...

**Comment by any1** [comment]
The problem is that the virtual keyboard protocol expects the user to set a keyboard layout for the virtual keyboard and thus the whole input device seat. This overrides the default layout and also other layouts if you have a multi-layout setup.

There are two possible solutions to this: Use a different seat or select a keyboard layout when starting wayvnc.

Creating a new seat and using it has the downside that some clients may not be multi-seat capable, but you can try it if you want:
```
swaymsg seat wayvnc fallback false # create a new seat
wayvnc --seat=wayvnc --keyboard=<layout>
```

Otherwise, just set the layout when running wayvnc:
```
wayvnc --keyboard=<layout>
```

We could also extract the layout from the selected seat and send it back into the virtual-keyboard protocol, but that would still not be a perfect solution, because the user may have selected multiple layouts, so he would be stuck with the one that was selected when wayvnc was run. There's a chance though that all the different layouts are passed via the interface, but I'll need to look into that.

**Comment by gabm** [comment]
both solutions work great! thank you...

**Comment by lahwaacz** [comment]
Interestingly, running wayvnc without `--seat` or `--keyboard` sets the keyboard layout to `us` and discards all other keyboard settings, but running with e.g. `--keyboard=cz` sets the keyboard layout and _preserves the other settings_ like `xkb_options "grp:alt_caps_toggle"` or `xkb_numlock enabled`.

**Comment by any1** [comment]
Yeah, I'm starting to think the compositor might be doing something not quite as intended.
