### ISSUE TITLE
Compose key does not work

### ISSUE THREAD

**Issue by Depau** [any1/wayvnc#61]
When I press compose on my local keyboard:

```
ERROR: Failed to look up keyboard symbol: Multi_key
```

For reproducing: compose can be enabled, for example, with `xkb_options shift:both_capslock_cancel,compose:caps` in sway config. This maps it to Caps lock and makes both shifts pressed together act like caps lock, one cancels.

**Comment by any1** [comment]
Have you tried running wayvnc with those xkb options set via the environment variable `XKB_DEFAULT_OPTIONS`? You could also try to mess with the options here: https://github.com/any1/wayvnc/blob/master/src/keyboard.c#L161. See: https://xkbcommon.org/doc/current/structxkb__rule__names.html

**Comment by any1** [comment]
If you're using tigervnc or any other client that supports the QEMU Extended Key Event, then these branches of wayvnc and neatvnc should take care of this problem: https://github.com/any1/wayvnc/tree/qemu-kb-ext and https://github.com/any1/neatvnc/tree/qemu-kb-ext

**Comment by any1** [comment]
I gave this a bit of a look and the qemu keyboard extension does indeed work around the issue. You just have to set `xkb_options` on the server side.

The problem with the "standard" method seems to be that if you have the same compose key on the vnc client side as on the server side, the client gets sent a `Multi_key` symbol instead of the original symbols. The `Multi_key` symbol is not a part of the keymap, so it doesn't know what to do with it. For the this to work, we might need to do some reverse mapping of `xkb_options`.

**Comment by any1** [comment]
Actually, with the following change it works fine:
```
[andri@galago wayvnc]$ git diff
diff --git a/src/keyboard.c b/src/keyboard.c
index 5877a46..c76b56d 100644
--- a/src/keyboard.c
+++ b/src/keyboard.c
@@ -166,6 +166,7 @@ int keyboard_init(struct keyboard* self, const char* layout, const char* variant
                .layout = layout,
                .model = "pc105",
                .variant = variant,
+               .options = "compose:menu",
        };
 
        self->keymap = xkb_keymap_new_from_names(self->context, &rule_names, 0);
```

That puts `Multi_key` into the keymap, so it can be looked up. Now what remains is to figure out how to make this "user friendly".

**Comment by any1** [comment]
See https://github.com/any1/wayvnc/blob/master/wayvnc.scd#L163-L167
